# Generated by Django 3.0.2 on 2020-06-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postandcomment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
