# Generated by Django 3.0.2 on 2020-07-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postandcomment', '0004_auto_20200623_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
